[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ==================== БИБЛИОТЕКИ ====================
lib_deps =
    ; JSON (лёгкий, быстрый)
    bblanchon/ArduinoJson @ ^7.3.1
    
    ; Сервопривод (аппаратный PWM для ESP32)
    madhephaestus/ESP32Servo @ ^3.0.5
    
    
    ; Датчики  (температура + давление + влажность)
    adafruit/DHT sensor library

; ==================== НАСТРОЙКИ СБОРКИ ====================
build_flags =
    ; Частота процессора (максимальная производительность)
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=0
    
    ; Оптимизация по размеру (экономит flash-память)
    -Os
    
    ; Увеличиваем стек для JSON (если будут глубокие объекты)
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    
    ; Включаем поддержку C++17 (для std::optional и т.д.)
    -std=c++17

; ==================== МОНИТОРИНГ ====================
monitor_filters =
    ; Убираем мусорные сообщения ESP32 при пробуждении
    esp32_exception_decoder
    time
    send_on_enter

